#!/bin/sh

if [ -d "/www/RadiusMonitor" ]; then
    rm -rf /www/RadiusMonitor
fi

if [ -d "/usr/share/RadiusMonitor" ]; then
    rm -rf /usr/share/RadiusMonitor
fi

if [ -d "/etc/freeradius3" ]; then
    rm -rf /etc/freeradius3
fi

sleep 1

git clone --depth 1 https://github.com/maizil41/RadiusMonitor.git /usr/share/RadiusMonitor

sleep 1

wget https://raw.githubusercontent.com/Maizil41/Mutiara-Wrt/main/Radmon_2.4.zip -O /Radmon_2.4.zip

unzip Radmon_2.4.zip

sleep 1

chmod +x /usr/bin/radmon-exec
chmod +x /usr/bin/radmon-log
chmod +x /usr/bin/radmon-kuota

sleep 1

ln -s /usr/share/RadiusMonitor /www/RadiusMonitor

sleep 1

cd /etc/freeradius3/mods-enabled
ln -s ../mods-available/always
ln -s ../mods-available/attr_filter
ln -s ../mods-available/chap
ln -s ../mods-available/detail
ln -s ../mods-available/digest
ln -s ../mods-available/eap
ln -s ../mods-available/exec
ln -s ../mods-available/expiration
ln -s ../mods-available/expr
ln -s ../mods-available/files
ln -s ../mods-available/logintime
ln -s ../mods-available/mschap
ln -s ../mods-available/pap
ln -s ../mods-available/preprocess
ln -s ../mods-available/radutmp
ln -s ../mods-available/realm
ln -s ../mods-available/sql
ln -s ../mods-available/sradutmp
ln -s ../mods-available/unix
cd

sleep 1

cd /etc/freeradius3/sites-enabled
ln -s ../sites-available/default
ln -s ../sites-available/inner-tunnel
cd

sleep 1

cd /www/RadiusMonitor && mysql -u root -pradius < radmon.sql

